##########
# title: collect every study's *_metrics.RDS into one place
##########
# Rscript collect_all_metrics.R
#
# For every study in R/study_registry.R (case_study/ is not, and never has
# been, in that registry - this naturally excludes it), find whichever
# *_metrics.RDS file(s) sit in the study's res_path, and:
#
#   1. copy them as-is into a destination tree, one subfolder per study, and
#   2. read them in, tag each row with study_name/category/source_file, and
#      row-bind everything into one combined table for cross-study analysis.
#
# Results only exist on the HPC (too large to sync here - see check_all.R's
# header), so like check_all.R this is written and syntax-tested locally but
# run for real on the HPC login node, or locally after syncing results/ down.
# Locally, every study will report "not_found" - that is expected, not a bug.
#
# Destination for the copies and the combined table is a sibling directory
# next to results/ itself (file.path(dirname(here()), "collected_metrics")),
# NOT inside the repo - same reasoning as why results/ isn't committed: this
# is heavy derived data, regenerated by re-running this script.
#
# Writes collect_metrics_status.csv next to this script (repo root) - a small
# per-study status table, committed like check_all_studies.csv, so progress
# is visible from this machine via `git pull` after a real run elsewhere.

library(here)
library(dplyr)
source(here("R", "pipeline.R"))
source(here("R", "study_registry.R"))

dest_root <- file.path(dirname(here()), "collected_metrics")
dir.create(dest_root, recursive = TRUE, showWarnings = FALSE)

#' Collect one study's metrics file(s)
#'
#' Globs res_path for *_metrics.RDS rather than hardcoding each study's exact
#' filename, since the on-disk convention is "however many *_metrics.RDS
#' files a study's *_metrics.R step(s) happened to write directly into
#' res_path". That one glob transparently handles:
#'   - the ordinary case of one file per study (e.g. bin_metrics.RDS)
#'   - model_evaluation, which can carry up to three in the same res_path
#'     (me_metrics.RDS / me_strat_metrics.RDS / me_split_metrics.RDS)
#'   - confidence_intervals/optimal_sf's two studies, which have no
#'     *_metrics.R step at all and so correctly glob to zero matches -
#'     reported below as "no_metrics_file", not an error.
collect_one <- function(row) {
  if (isTRUE(row$blocked)) {
    return(list(
      status = data.frame(study_name = row$study_name, category = row$category,
                           files_found = NA_integer_, files_copied = NA_integer_,
                           files_combined = NA_integer_,
                           status = "blocked", stringsAsFactors = FALSE),
      metrics = list()
    ))
  }

  study <- load_study(row$config_path, row$config_var)
  files <- list.files(study$res_path, pattern = "_metrics\\.RDS$",
                      full.names = TRUE)

  if (length(files) == 0) {
    return(list(
      status = data.frame(study_name = row$study_name, category = row$category,
                           files_found = 0L, files_copied = 0L, files_combined = 0L,
                           status = if (dir.exists(study$res_path)) "no_metrics_file" else "not_found",
                           stringsAsFactors = FALSE),
      metrics = list()
    ))
  }

  study_dest <- file.path(dest_root, row$study_name)
  dir.create(study_dest, recursive = TRUE, showWarnings = FALSE)

  copied <- 0L
  # Every study's *_metrics.R produces a flat tibble EXCEPT
  # validation/continuous's cts_val_metrics.RDS, which is a named list of
  # four differently-shaped tibbles (subgroups/variances/var_imps/top_var) -
  # its own study-specific breakdown, not "one row per run". Such files are
  # still copied byte-for-byte (copying doesn't care about internal shape),
  # just excluded from the cross-study combined table, which only makes
  # sense for a common flat-tibble schema.
  metrics <- lapply(files, function(f) {
    ok <- file.copy(f, file.path(study_dest, basename(f)), overwrite = TRUE)
    if (ok) copied <<- copied + 1L

    tryCatch({
      obj <- readRDS(f)
      if (!is.data.frame(obj)) {
        message("collect_all_metrics: ", f,
                " is not a flat tibble (", class(obj)[1],
                ") - copied but left out of the combined table")
        return(NULL)
      }
      obj %>%
        mutate(study_name = row$study_name, category = row$category,
               source_file = basename(f))
    }, error = function(e) {
      message("collect_all_metrics: failed to read ", f, ": ", conditionMessage(e))
      NULL
    })
  })
  metrics <- metrics[!vapply(metrics, is.null, logical(1))]

  list(
    status = data.frame(study_name = row$study_name, category = row$category,
                        files_found = length(files), files_copied = copied,
                        files_combined = length(metrics),
                        status = "collected", stringsAsFactors = FALSE),
    metrics = metrics
  )
}

results <- lapply(seq_len(nrow(study_registry)), function(i) {
  row <- study_registry[i, ]
  tryCatch(
    collect_one(row),
    error = function(e) list(
      status = data.frame(study_name = row$study_name, category = row$category,
                          files_found = NA_integer_, files_copied = NA_integer_,
                          files_combined = NA_integer_,
                          status = paste("ERROR:", conditionMessage(e)),
                          stringsAsFactors = FALSE),
      metrics = list()
    )
  )
})

status <- bind_rows(lapply(results, `[[`, "status")) %>%
  arrange(category, study_name)

all_metrics_list <- unlist(lapply(results, `[[`, "metrics"), recursive = FALSE)

# ---- console ----

print(status, row.names = FALSE)

cat("\n=== TOTALS ===\n")
cat("Studies collected:  ", sum(status$status == "collected"), "\n")
cat("Files found:        ", sum(status$files_found, na.rm = TRUE), "\n")
cat("Files copied:       ", sum(status$files_copied, na.rm = TRUE), "\n")
cat("Files combined:     ", sum(status$files_combined, na.rm = TRUE), "\n")
cat("\nBy status:\n")
print(table(status$status))

# ---- combined table ----
# bind_rows() fills columns a given study's metrics tibble doesn't have with
# NA rather than erroring - e.g. the missing-data studies carry
# mechanism/method columns other studies don't. That is the desired behavior
# here: one wide combined table, not a hard schema match across studies.
if (length(all_metrics_list) > 0) {
  all_metrics <- bind_rows(all_metrics_list)
  saveRDS(all_metrics, file.path(dest_root, "all_metrics.RDS"))
  write.csv(all_metrics, file.path(dest_root, "all_metrics.csv"), row.names = FALSE)
  cat("\nCombined table: ", nrow(all_metrics), "rows from",
      length(all_metrics_list), "metrics file(s), written to\n  ",
      file.path(dest_root, "all_metrics.RDS"), "\n  ",
      file.path(dest_root, "all_metrics.csv"), "\n")
} else {
  cat("\nNo metrics files found anywhere - no combined table written.\n")
}

# ---- status csv ----

status_path <- here("collect_metrics_status.csv")
write.csv(status, status_path, row.names = FALSE)
cat("\nWrote", status_path, "\n")
cat("Copies + combined table under", dest_root, "\n")
