---
title: "simulation updates"
author: "Ellie Van Vogt"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r libraries}
library(ggplot2)
library(purrr)
```


```{r results}
cate_corr <- readRDS("/rds/general/user/evanvogt/projects/nihr_drf_simulations/live/results/all/cate_correlations.RDS")

cate_mse <- readRDS("/rds/general/user/evanvogt/projects/nihr_drf_simulations/live/results/all/cate_mses.RDS")

cate_coverage <- readRDS("/rds/general/user/evanvogt/projects/nihr_drf_simulations/live/results/all/cate_coverage.RDS")

```



```{r summarise across 1000 scenarios, echo = FALSE}

coverage_df <- map_dfr(names(cate_coverage), function(scenario) {
  map_dfr(names(cate_coverage[[scenario]]), function(n) {
    map_dfr(names(cate_coverage[[scenario]][[n]]), function(model) {
      data.frame(
        scenario = scenario,
        n = as.numeric(n),
        model = model,
        coverage = mean(cate_coverage[[scenario]][[n]][[model]])
      )
    })
  })
})

corr_df <- map_dfr(names(cate_corr), function(scenario) {
  map_dfr(names(cate_corr[[scenario]]), function(n) {
    map_dfr(names(cate_corr[[scenario]][[n]]), function(model) {
      data.frame(
        scenario = scenario,
        n = as.numeric(n),
        model = model,
        corr = mean(cate_corr[[scenario]][[n]][[model]], na.rm = T)
      )
    })
  })
})

mse_df <- map_dfr(names(cate_mse), function(scenario) {
  map_dfr(names(cate_mse[[scenario]]), function(n) {
    map_dfr(names(cate_mse[[scenario]][[n]]), function(model) {
      data.frame(
        scenario = scenario,
        n = as.numeric(n),
        model = model,
        mse = mean(cate_mse[[scenario]][[n]][[model]], na.rm = T)
      )
    })
  })
})

```

Note that the `echo = FALSE` parameter was added to the code chunk to prevent printing of the R code that generated the plot.

```{r coverage plots}


  ggplot(coverage_df, aes(x = model, y = coverage, fill = model)) +
  geom_bar(stat = "identity", position = "dodge") +
  facet_grid(n ~ scenario) + 
  theme_minimal() +
  labs(title = "CATE Coverage Across Scenarios and Sample Sizes",
       x = "Model",
       y = "Coverage")

```


```{r mse plots}
ggplot(mse_df, aes(x = model, y = mse, fill = model)) +
  geom_bar(stat = "identity", position = "dodge") +
  facet_grid(n ~ scenario) + 
  theme_minimal() +
  labs(title = "CATE MSE Across Scenarios and Sample Sizes",
       x = "Model",
       y = "MSE")
```

```{r}
ggplot(corr_df, aes(x = model, y = corr, fill = model)) +
  geom_bar(stat = "identity", position = "dodge") +
  facet_grid(n ~ scenario) + 
  theme_minimal() +
  labs(title = "CATE Correlation Across Scenarios and Sample Sizes",
       x = "Model",
       y = "Correlation")
```



