---
title: "simulation updates"
author: "Ellie Van Vogt"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r libraries, include=FALSE}
library(ggplot2)
library(paletteer)
library(gridExtra)
library(dplyr)
library(purrr)
```


```{r results}
cate_corr <- readRDS("/rds/general/user/evanvogt/projects/nihr_drf_simulations/live/results/binary/all/cate_correlations.RDS")

cate_mse <- readRDS("/rds/general/user/evanvogt/projects/nihr_drf_simulations/live/results/binary/all/cate_mses.RDS")

cate_coverage <- readRDS("/rds/general/user/evanvogt/projects/nihr_drf_simulations/live/results/binary/all/cate_coverage.RDS")

cate_bias <- readRDS("/rds/general/user/evanvogt/projects/nihr_drf_simulations/live/results/binary/all/cate_bias.RDS")

ci_length <- readRDS("/rds/general/user/evanvogt/projects/nihr_drf_simulations/live/results/binary/all/ci_length.RDS")

BLP_df <- readRDS("/rds/general/user/evanvogt/projects/nihr_drf_simulations/live/results/binary/all/BLP_tests_metrics.RDS")

```

```{r functions}
create_summary_df <- function(nested_list, summary_name = "coverage") {
  map_dfr(names(nested_list), function(scenario) {
    map_dfr(names(nested_list[[scenario]]), function(n) {
      map_dfr(names(nested_list[[scenario]][[n]]), function(model) {
        df <- data.frame(
          scenario = as.numeric(gsub("scenario_", "", scenario)), 
          n = as.factor(n),
          model = model
        )
        df[[summary_name]] <- mean(nested_list[[scenario]][[n]][[model]])
        df$mcse <- sd(nested_list[[scenario]][[n]][[model]])/sqrt(1000)
        df <- df %>% mutate(
          lb = df[[summary_name]] + qnorm(0.025)*mcse,
          ub = df[[summary_name]] + qnorm(0.975)*mcse
        )
        df <- df %>% arrange(scenario)
        df
      })
    })
  })
}

plot_all <- function(df, bench, var, title) {
  ggplot(df, aes(x = model, y = .data[[var]], colour = model)) +
    geom_point() + 
    geom_segment(aes(x = model, xend = model, y = bench, yend = .data[[var]])) +
    facet_grid(n ~ scenario) + 
    theme_minimal() +
    theme(
      axis.title.x = element_blank(),
      axis.text.x = element_blank(),
      axis.ticks.x = element_blank()
    ) +
    labs(
      title = title,
      x = "Model",
      y = var
    )
}

plot_all_scenario <- function(df, bench, var, title) {
  scenario_plots <- lapply(unique(df$scenario), function(scenario) {
    p <- ggplot(df[df$scenario == scenario, ], aes(x = model, y = .data[[var]], colour = model)) +
      geom_point() + 
      geom_segment(aes(x = model, xend = model, y = bench, yend = .data[[var]])) +
      facet_wrap(~ n) +  # Facet by sample size
      theme_minimal() +
      theme(
        axis.title.x = element_blank(),
        axis.text.x = element_text(angle = 90, vjust = 0.5, hjust = 1),
        axis.ticks.x = element_blank()
      ) +
      labs(
        title = paste(title, "-", scenario),
        x = "Model",
        y = var
      )
    
    return(p)
  })
  
  names(scenario_plots) <- unique(df$scenario)  # Name list elements by scenario
  return(scenario_plots)
}

plot_MCSE <- function(df, var, title) {
  ggplot(df, aes(x = model, y = .data[[var]], colour = model)) +
    geom_point() + 
    geom_segment(aes(x = model, xend = model, y = lb, yend = ub)) +
    facet_grid(n ~ scenario) + 
    theme_minimal() +
    theme(
      axis.title.x = element_blank(),
      axis.text.x = element_text(angle = 90, vjust = 0.5, hjust = 1),
      axis.ticks.x = element_blank()
    ) +
    labs(
      title = title,
      x = "Model",
      y = var
    )
}

plot_MCSE_scenario <- function(df, var, title) {
  scenario_plots <- lapply(unique(df$scenario), function(scenario) {
    p <- ggplot(df[df$scenario == scenario, ], aes(x = model, y = .data[[var]], colour = model)) +
      geom_point() + 
      geom_segment(aes(x = model, xend = model, y = lb, yend = ub)) +
      facet_wrap(~ n) +  # Facet by sample size instead of scenario
      theme_minimal() +
      theme(
        axis.title.x = element_blank(),
        axis.text.x = element_text(angle = 90, vjust = 0.5, hjust = 1),
        axis.ticks.x = element_blank()
      ) +
      labs(
        title = paste(title, "-", scenario),
        x = "Model",
        y = var
      )
    
    return(p)
  })
  
  names(scenario_plots) <- unique(df$scenario)  # Name list elements by scenario
  return(scenario_plots)
}
```


```{r summarise across 1000 scenarios, include=FALSE}

coverage_df  <- create_summary_df(cate_coverage, "coverage")

corr_df <- create_summary_df(cate_corr, "correlation")

mse_df <- create_summary_df(cate_mse, "mse")

bias_df <- create_summary_df(cate_bias, "bias")

ci_df <- create_summary_df(ci_length, "length")

```


Note that the `echo = FALSE` parameter was added to the code chunk to prevent printing of the R code that generated the plot.

```{r coverage plots}

plot_MCSE(coverage_df, "coverage", "CATE Coverage Across Scenarios and Sample Sizes")

plot_MCSE_scenario(coverage_df, "coverage", "CATE Coverage Across Scenarios and Sample Sizes")

```


```{r mse plots}

plot_MCSE(mse_df, "mse", "CATE MSE Across Scenarios and Sample Sizes")

plot_MCSE_scenario(mse_df, "mse", "CATE MSE Across Scenarios and Sample Sizes")

```

```{r}

plot_all(corr_df, 0, "correlation", "CATE Correlation Across Scenarios and Sample Sizes")

plot_all_scenario(corr_df, 0, "correlation", "CATE Correlation Across Scenarios and Sample Sizes")

```

```{r}

plot_MCSE(bias_df, "bias", "CATE Bias Across Scenarios and Sample Sizes")

plot_MCSE_scenario(bias_df, "bias", "CATE Bias Across Scenarios and Sample Sizes")

```

```{r}

plot_MCSE(ci_df, "length", "CATE CI Length Across Scenarios and Sample Sizes")

plot_MCSE_scenario(ci_df, "length", "CATE CI Length Across Scenarios and Sample Sizes")

```

```{r}
# BLP metrics

BLP_df <- BLP_df %>% mutate(
  TP = TP/1000,
  FP = FP/1000,
  TN = TN/1000,
  FN = FN/1000,
  scenario = as.numeric(gsub("scenario_", "", scenario))
)
plot_all(BLP_df, 0, "FN", "proportion of false negatives across all sample sizes and scenarios")
plot_all(BLP_df, 0, "TP", "proportion of true positives across all sample sizes and scenarios")
plot_all(BLP_df, 0, "sensitivity", "Sensitivity across all sample sizes and scenarios")

BLP_df <- BLP_df %>%
  mutate(agreement = ifelse(scenario == 1, TN, TP),
         disagreement = ifelse(scenario == 1, FP, FN),
         n = as.factor(n)) %>%
  filter(n != 5000) 

plot_all(BLP_df, 0, "agreement", "agreement of models with underlying DGM")
```

```{r}
plot_all_scenario(BLP_df, 0, "TP", "proportion of true positives across all sample sizes and scenarios")

```
scratch stuff for poster
```{r}
jitter <- position_jitter(0.1, seed = 1998)
mse_plot <- mse_df <- mse_df
  ggplot(mse_df, aes(x = n, y = mse, colour = model)) +
    geom_point(position = jitter) + 
    geom_segment(aes(x = n, xend = n, y = lb, yend = ub), position = jitter) +
    facet_grid(cols = vars(scenario)) + 
    theme_minimal() +
    theme(
      axis.title.x = element_blank(),
      axis.text.x = element_text(angle = 90, vjust = 0.5, hjust = 1),
      axis.ticks.x = element_blank()
    ) +
    labs(
      title = "Average MSE in individual CATE predictions",
      x = "Model",
      y = "MSE"
    ) + 
    scale_color_paletteer_d("MetBrewer::Austria")
```
scratch
```{r}
jitter <- position_jitter(0.2, seed = 1998)

bias_plot <- ggplot(bias_df, aes(x = n, y = bias, colour = model)) +
  geom_hline(yintercept = 0) +
  geom_point(position = jitter) + 
  geom_segment(aes(x = n, xend = n, y = lb, yend = ub), position = jitter) +
  facet_grid(cols = vars(scenario)) + 
  theme_minimal() +
  theme(
    axis.title.x = element_blank(),
    axis.text.x = element_text(angle = 90, vjust = 0.5, hjust = 1),
    axis.ticks.x = element_blank()
    ) +
  labs(
    title = "Average bias in individual CATE predictions",
    x = "Model",
    y = "Bias"
    ) + 
  scale_color_paletteer_d("MetBrewer::Austria")
  
plot_MCSE(bias_df, "bias", "Average bias in individual CATE predictions") + scale_color_paletteer_d("MetBrewer::Austria")
```

```{r}
jitter <- position_jitter(width = 0.1, seed = 1998)
  ggplot(BLP_df, aes(x = n, y = agreement, fill = model)) +
    geom_bar(stat = "identity", position = "dodge", alpha = 0.9, width = 0.7) +
    #geom_point(position = jitter) + 
    #geom_segment(aes(x = n, xend = n, y = 0, yend = agreement)) +
    facet_grid(cols = vars(scenario)) + 
    theme_minimal() +
    theme(
      axis.title.x = element_blank(),
      axis.text.x = element_text(angle = 90, vjust = 0.5, hjust = 1),
      axis.ticks.x = element_blank()
    ) +
    labs(
      title = "Agreement proportions between BLP and DGM",
      x = "Model",
      y = "Agreement"
    ) +
  scale_fill_paletteer_d("MetBrewer::Austria")
  
  BLP_df <- BLP_df %>%
  mutate(jittered_x = as.numeric(n) + runif(n(), -0.3, 0.3))  # Convert factor to numeric for jittering

ggplot(BLP_df, aes(x = jittered_x, y = agreement, colour = model)) +
  geom_segment(aes(x = jittered_x, xend = jittered_x, y = 0, yend = agreement)) +
  geom_point() + 
  facet_grid(cols = vars(scenario)) + 
  theme_minimal() +
  theme(
    axis.title.x = element_blank(),
    axis.text.x = element_text(angle = 90, vjust = 0.5, hjust = 1),
    axis.ticks.x = element_blank()
  ) +
  labs(
    title = "Agreement with underlying DGM",
    x = "Model",
    y = "Agreement"
  ) + 
  scale_x_continuous(breaks = unique(as.numeric(BLP_df$n)), labels = levels(BLP_df$n)) +  # Keep categorical labels
  scale_color_paletteer_d("MetBrewer::Austria")
```
```{r}

jitter <- position_jitter(0.2, seed = 1998)
ggplot(coverage_df, aes(x = n, y = coverage, colour = model)) +
  geom_point(position = jitter) + 
  geom_segment(aes(x = n, xend = n, y = lb, yend = ub), position = jitter) +
  facet_grid(cols = vars(scenario)) + 
  theme_minimal() +
  theme(
    axis.title.x = element_blank(),
    axis.text.x = element_text(angle = 90, vjust = 0.5, hjust = 1),
    axis.ticks.x = element_blank()
    ) +
  labs(
    title = "Average coverage of individual CATE predictions",
    x = "Model",
    y = "coverage"
    ) + 
  scale_color_paletteer_d("MetBrewer::Austria")
```

